import { useState } from "react";
import { Alert, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useCctv } from "@/lib/cctv-context";
import { useColors } from "@/hooks/use-colors";
import { useRouter } from "expo-router";

export default function CamerasScreen() {
  const colors = useColors();
  const router = useRouter();
  const { cameras, authorized, addCamera, removeCamera } = useCctv();
  const [name, setName] = useState("");
  const [url, setUrl] = useState("");
  const [location, setLocation] = useState("");
  const save = async () => { const result = await addCamera({ name, url, location }); Alert.alert(result.ok ? "Tersimpan" : "Tidak dapat disimpan", result.message); if (result.ok) { setName(""); setUrl(""); setLocation(""); } };
  return <ScreenContainer className="px-5 pt-4"><Text className="text-3xl font-bold text-foreground">Kamera</Text><Text className="mt-2 text-sm leading-5 text-muted">Tambahkan hanya kamera yang Anda miliki atau kelola. Kredensial tidak diproses oleh aplikasi ini.</Text><View style={[styles.form, { borderColor: colors.border, backgroundColor: colors.surface }]}><TextInput placeholder="Nama kamera" placeholderTextColor={colors.muted} value={name} onChangeText={setName} style={[styles.input, { color: colors.foreground, borderColor: colors.border }]} /><TextInput placeholder="rtsp://192.168.1.20:554/stream" placeholderTextColor={colors.muted} value={url} onChangeText={setUrl} autoCapitalize="none" autoCorrect={false} style={[styles.input, { color: colors.foreground, borderColor: colors.border }]} /><TextInput placeholder="Lokasi (opsional)" placeholderTextColor={colors.muted} value={location} onChangeText={setLocation} style={[styles.input, { color: colors.foreground, borderColor: colors.border }]} /><Pressable onPress={save} style={({ pressed }) => [styles.button, { backgroundColor: authorized ? colors.primary : colors.border }, pressed && { opacity: 0.72 }]}><Text style={styles.buttonText}>{authorized ? "Simpan kamera berizin" : "Aktifkan otorisasi di Dashboard"}</Text></Pressable></View><Text className="mt-6 text-lg font-bold text-foreground">Kamera tersimpan</Text><FlatList data={cameras} keyExtractor={(item) => item.id} contentContainerStyle={{ gap: 10, paddingTop: 12, paddingBottom: 28 }} ListEmptyComponent={<Text className="text-sm text-muted">Belum ada kamera tersimpan.</Text>} renderItem={({ item }) => <View style={[styles.card, { borderColor: colors.border, backgroundColor: colors.surface }]}><View className="flex-row items-center justify-between"><View className="flex-1"><Text className="text-base font-semibold text-foreground">{item.name}</Text><Text className="mt-1 text-xs text-muted">{item.url}</Text></View><Pressable onPress={() => removeCamera(item.id)}><Text style={{ color: colors.error, fontSize: 12, fontWeight: "700" }}>Hapus</Text></Pressable></View><View className="mt-3 flex-row gap-2"><Pressable onPress={() => router.push({ pathname: "/camera-viewer" as any, params: { id: item.id } })} style={[styles.outline, { borderColor: colors.primary }]}><Text style={{ color: colors.primary, fontWeight: "800", fontSize: 12 }}>Buka viewer</Text></Pressable><Pressable onPress={() => Alert.alert("Uji koneksi", "Uji koneksi membutuhkan kamera aktif dan URL yang benar. Tidak ada kredensial yang ditebak atau dikirim ke layanan pihak ketiga.")} style={[styles.outline, { borderColor: colors.border }]}><Text style={{ color: colors.foreground, fontWeight: "700", fontSize: 12 }}>Uji koneksi</Text></Pressable></View></View>} /></ScreenContainer>;
}
const styles = StyleSheet.create({ form: { marginTop: 18, borderWidth: 1, borderRadius: 20, padding: 16, gap: 10 }, input: { borderWidth: 1, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 12, fontSize: 13 }, button: { minHeight: 46, borderRadius: 14, alignItems: "center", justifyContent: "center", paddingHorizontal: 10 }, buttonText: { color: "#06120F", fontWeight: "800", fontSize: 12 }, card: { borderWidth: 1, borderRadius: 18, padding: 16 }, outline: { borderWidth: 1, borderRadius: 11, paddingVertical: 9, paddingHorizontal: 11 } });
