import { Alert, Pressable, ScrollView, Share, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useCctv } from "@/lib/cctv-context";
import { useColors } from "@/hooks/use-colors";
import { AlertBanner } from "@/components/ui/alert-banner";

export default function SettingsScreen() {
  const colors = useColors();
  const { audits, setAuthorized, storageError, clearStorageError } = useCctv();
  const exportAuditLog = async () => {
    const safeEntries = audits.map(({ id, scope, createdAt, result, note }) => ({ id, scope, createdAt, result, note }));
    const message = JSON.stringify({ app: "Setankober.cctv", exportedAt: new Date().toISOString(), entries: safeEntries }, null, 2);
    try { await Share.share({ title: "Setankober.cctv audit log", message }); } catch { Alert.alert("Ekspor gagal", "Audit log tetap tersimpan lokal dan tidak berubah."); }
  };
  return <ScreenContainer className="px-5 pt-4"><ScrollView contentContainerStyle={{ paddingBottom: 32 }}>{storageError && <AlertBanner title="DATA LOKAL BERMASALAH" message={storageError} tone="warning" colors={colors} onDismiss={clearStorageError} />}<Text style={{ color: colors.foreground }} className="text-3xl font-bold">Settings</Text><Text style={{ color: colors.muted }} className="mt-2 text-sm leading-5">Kontrol privasi, keselamatan, dan riwayat audit lokal.</Text><View className="mt-6 gap-3"><SettingCard title="Safety Center" description="Fitur dibatasi pada aset berizin. Tidak ada brute force, credential guessing, atau pemindaian internet publik." colors={colors} /><SettingCard title="Penyimpanan" description={`Riwayat audit tersimpan lokal. ${audits.length} catatan saat ini.`} colors={colors} /><SettingCard title="License" description="MIT License untuk kode aplikasi. Gunakan sesuai hukum dan kebijakan perangkat Anda." colors={colors} /></View><Pressable onPress={exportAuditLog} style={({ pressed }) => [styles.secondary, { borderColor: colors.primary }, pressed && { opacity: 0.72 }]}><Text style={{ color: colors.primary, fontWeight: "800" }}>Ekspor audit log aman</Text></Pressable><Text style={{ color: colors.muted }} className="mt-2 text-xs leading-5">Ekspor hanya berisi metadata audit, bukan password, token, atau kredensial kamera.</Text><Pressable onPress={() => { setAuthorized(false); Alert.alert("Otorisasi dimatikan", "Audit dan penambahan kamera akan diblokir."); }} style={({ pressed }) => [styles.danger, { borderColor: colors.error }, pressed && { opacity: 0.72 }]}><Text style={{ color: colors.error, fontWeight: "800" }}>Matikan otorisasi</Text></Pressable><Text style={{ color: colors.muted }} className="mt-6 text-xs leading-5">Setankober.cctv 1.0.0 · Data kamera tidak disinkronkan ke cloud secara default.</Text></ScrollView></ScreenContainer>;
}
function SettingCard({ title, description, colors }: { title: string; description: string; colors: ReturnType<typeof useColors> }) { return <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={{ color: colors.foreground }} className="text-base font-semibold">{title}</Text><Text style={{ color: colors.muted }} className="mt-2 text-xs leading-5">{description}</Text></View>; }
const styles = StyleSheet.create({ card: { borderWidth: 1, borderRadius: 18, padding: 16 }, secondary: { marginTop: 20, minHeight: 46, borderWidth: 1, borderRadius: 14, alignItems: "center", justifyContent: "center" }, danger: { marginTop: 12, minHeight: 46, borderWidth: 1, borderRadius: 14, alignItems: "center", justifyContent: "center" } });
